project:
  type: website
  output-dir: docs
  resources:
    - cv/cv_fan_yin.pdf
    - files/favicon.ico

website:
  title: "Fan Yin"
  favicon: "files/favicon.ico"
  search: false
  google-analytics: 
    tracking-id: "G-ZRYLHTQ3PF"
    storage: none
    

  navbar:
    left:
      - text: Home  
        href: index.qmd
      - research.qmd
      - teaching.qmd
      - cv.qmd
    
    right:
      - icon: envelope-at
        href: mailto:fan.yin@hu-berlin.de
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/fan-yin-4b6481163
        target: _blank

  page-footer: 
    left:
      - icon: c-circle
        text: 2026 Fan Yin

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [simplex, simplex_light.scss]
      dark: [simplex, simplex_dark.scss]
    css: styles.css
    toc: false
    page-layout: full



